const ERROR_CODES = {
    // ========== AUTHENTICATION ERRORS (401xx) ==========
    // General Authentication
    AUTH_TOKEN_MISSING: 40101,
    AUTH_TOKEN_INVALID: 40102,
    AUTH_TOKEN_EXPIRED: 40103,
    AUTH_TOKEN_MALFORMED: 40104,

    // Login/Registration
    AUTH_INVALID_CREDENTIALS: 40110,
    AUTH_USER_NOT_FOUND: 40111,
    AUTH_PASSWORD_INCORRECT: 40112,
    AUTH_EMAIL_NOT_VERIFIED: 40113,
    AUTH_ACCOUNT_LOCKED: 40114,
    AUTH_ACCOUNT_SUSPENDED: 40115,
    AUTH_ACCOUNT_DELETED: 40116,
    AUTH_LOGIN_ATTEMPTS_EXCEEDED: 40117,

    // Password Related
    AUTH_PASSWORD_TOO_WEAK: 40120,
    AUTH_PASSWORD_PREVIOUSLY_USED: 40121,
    AUTH_PASSWORD_RESET_TOKEN_INVALID: 40122,
    AUTH_PASSWORD_RESET_TOKEN_EXPIRED: 40123,

    // ========== VALIDATION ERRORS (400xx) ==========
    // General Validation
    VALIDATION_GENERAL_ERROR: 40001,
    VALIDATION_MISSING_REQUIRED_FIELD: 40002,
    VALIDATION_INVALID_FORMAT: 40003,
    VALIDATION_INVALID_LENGTH: 40004,
    VALIDATION_INVALID_RANGE: 40005,
    VALIDATION_INVALID_TYPE: 40006,

    // Email Validation
    VALIDATION_EMAIL_INVALID: 40010,
    VALIDATION_EMAIL_DUPLICATE: 40011,
    VALIDATION_EMAIL_BLACKLISTED: 40012,
    VALIDATION_EMAIL_DOMAIN_NOT_ALLOWED: 40013,

    // Password Validation
    VALIDATION_PASSWORD_TOO_SHORT: 40020,
    VALIDATION_PASSWORD_TOO_LONG: 40021,
    VALIDATION_PASSWORD_NO_UPPERCASE: 40022,
    VALIDATION_PASSWORD_NO_LOWERCASE: 40023,
    VALIDATION_PASSWORD_NO_NUMBER: 40024,
    VALIDATION_PASSWORD_NO_SPECIAL_CHAR: 40025,
    VALIDATION_PASSWORD_MISMATCH: 40026,

    // Phone Number Validation
    VALIDATION_PHONE_INVALID: 40030,
    VALIDATION_PHONE_DUPLICATE: 40031,
    VALIDATION_PHONE_COUNTRY_CODE_MISSING: 40032,

    // Date Validation
    VALIDATION_DATE_INVALID: 40040,
    VALIDATION_DATE_PAST: 40041,
    VALIDATION_DATE_FUTURE: 40042,
    VALIDATION_DATE_RANGE_INVALID: 40043,

    // File Validation
    VALIDATION_FILE_REQUIRED: 40050,
    VALIDATION_FILE_TYPE_INVALID: 40051,
    VALIDATION_FILE_SIZE_TOO_LARGE: 40052,
    VALIDATION_FILE_SIZE_TOO_SMALL: 40053,
    VALIDATION_FILE_CORRUPTED: 40054,
    VALIDATION_FILE_VIRUS_DETECTED: 40055,

    // ID/Reference Validation
    VALIDATION_ID_INVALID: 40060,
    VALIDATION_REFERENCE_NOT_FOUND: 40061,
    VALIDATION_CIRCULAR_REFERENCE: 40062,

    // ========== FORBIDDEN ERRORS (403xx) ==========
    // Permissions
    FORBIDDEN_INSUFFICIENT_PERMISSIONS: 40301,
    FORBIDDEN_ROLE_NOT_AUTHORIZED: 40302,
    FORBIDDEN_RESOURCE_ACCESS_DENIED: 40303,
    FORBIDDEN_ACTION_NOT_ALLOWED: 40304,

    // Account Status
    FORBIDDEN_ACCOUNT_INACTIVE: 40310,
    FORBIDDEN_ACCOUNT_PENDING: 40311,
    FORBIDDEN_ACCOUNT_BANNED: 40312,
    FORBIDDEN_ACCOUNT_EXPIRED: 40313,

    // Business Rules
    FORBIDDEN_OPERATION_NOT_ALLOWED: 40320,
    FORBIDDEN_TIME_RESTRICTION: 40321,
    FORBIDDEN_QUOTA_EXCEEDED: 40322,
    FORBIDDEN_MAINTENANCE_MODE: 40323,

    // ========== NOT FOUND ERRORS (404xx) ==========
    // Users
    NOT_FOUND_USER: 40401,
    NOT_FOUND_USER_PROFILE: 40402,

    // Organizations
    NOT_FOUND_ORGANIZATION: 40410,
    NOT_FOUND_ORGANIZATION_PROFILE: 40411,
    NOT_FOUND_ORGANIZATION_BRANCH: 40412,

    // Reviews
    NOT_FOUND_REVIEW: 40420,
    NOT_FOUND_REVIEW_COMMENT: 40421,

    // MOU
    NOT_FOUND_MOU: 40430,
    NOT_FOUND_MOU_DOCUMENT: 40431,
    NOT_FOUND_MOU_VERSION: 40432,

    // Roadshow
    NOT_FOUND_ROADSHOW: 40440,
    NOT_FOUND_ROADSHOW_EVENT: 40441,
    NOT_FOUND_ROADSHOW_REGISTRATION: 40442,

    // Files
    NOT_FOUND_FILE: 40450,
    NOT_FOUND_IMAGE: 40451,
    NOT_FOUND_DOCUMENT: 40452,

    // General Resources
    NOT_FOUND_RESOURCE: 40460,
    NOT_FOUND_ENDPOINT: 40461,
    NOT_FOUND_PAGE: 40462,

    // ========== CONFLICT ERRORS (409xx) ==========
    // Data Conflicts
    CONFLICT_DUPLICATE_ENTRY: 40901,
    CONFLICT_UNIQUE_CONSTRAINT: 40902,
    CONFLICT_VERSION_MISMATCH: 40903,
    CONFLICT_CONCURRENT_MODIFICATION: 40904,

    // Business Logic Conflicts
    CONFLICT_ORGANIZATION_ALREADY_EXISTS: 40910,
    CONFLICT_REVIEW_ALREADY_SUBMITTED: 40911,
    CONFLICT_MOU_ALREADY_SIGNED: 40912,
    CONFLICT_ROADSHOW_ALREADY_REGISTERED: 40913,
    CONFLICT_USER_ALREADY_REGISTERED: 40914,

    // State Conflicts
    CONFLICT_INVALID_STATE_TRANSITION: 40920,
    CONFLICT_RESOURCE_LOCKED: 40921,
    CONFLICT_OPERATION_IN_PROGRESS: 40922,

    // ========== UNPROCESSABLE ENTITY ERRORS (422xx) ==========
    // Business Rules
    UNPROCESSABLE_BUSINESS_RULE_VIOLATION: 42201,
    UNPROCESSABLE_INVALID_OPERATION: 42202,
    UNPROCESSABLE_PREREQUISITE_NOT_MET: 42203,

    // Data Integrity
    UNPROCESSABLE_DATA_INTEGRITY_VIOLATION: 42210,
    UNPROCESSABLE_REFERENTIAL_INTEGRITY: 42211,
    UNPROCESSABLE_CONSTRAINT_VIOLATION: 42212,

    // Workflow
    UNPROCESSABLE_WORKFLOW_VIOLATION: 42220,
    UNPROCESSABLE_STATUS_CHANGE_INVALID: 42221,
    UNPROCESSABLE_APPROVAL_REQUIRED: 42222,

    // ========== RATE LIMIT ERRORS (429xx) ==========
    RATE_LIMIT_EXCEEDED: 42901,
    RATE_LIMIT_API_QUOTA_EXCEEDED: 42902,
    RATE_LIMIT_DAILY_LIMIT_EXCEEDED: 42903,
    RATE_LIMIT_HOURLY_LIMIT_EXCEEDED: 42904,

    // ========== SERVER ERRORS (500xx) ==========
    // General Server Errors
    SERVER_INTERNAL_ERROR: 50001,
    SERVER_CONFIGURATION_ERROR: 50002,
    SERVER_MAINTENANCE_MODE: 50003,
    SERVER_OVERLOADED: 50004,

    // Database Errors
    DATABASE_CONNECTION_ERROR: 50010,
    DATABASE_QUERY_ERROR: 50011,
    DATABASE_TRANSACTION_ERROR: 50012,
    DATABASE_DEADLOCK: 50013,
    DATABASE_TIMEOUT: 50014,
    DATABASE_INTEGRITY_ERROR: 50015,

    // File System Errors
    FILE_SYSTEM_ERROR: 50020,
    FILE_UPLOAD_ERROR: 50021,
    FILE_DELETE_ERROR: 50022,
    FILE_MOVE_ERROR: 50023,
    FILE_PERMISSION_ERROR: 50024,

    // External Service Errors
    EXTERNAL_SERVICE_UNAVAILABLE: 50030,
    EXTERNAL_SERVICE_TIMEOUT: 50031,
    EXTERNAL_SERVICE_ERROR: 50032,
    EXTERNAL_API_ERROR: 50033,

    // Email Service Errors
    EMAIL_SERVICE_ERROR: 50040,
    EMAIL_SEND_FAILED: 50041,
    EMAIL_TEMPLATE_ERROR: 50042,

    // Cache Errors
    CACHE_ERROR: 50050,
    CACHE_CONNECTION_ERROR: 50051,
    CACHE_WRITE_ERROR: 50052,
    CACHE_READ_ERROR: 50053,

    // ========== SERVICE UNAVAILABLE ERRORS (503xx) ==========
    SERVICE_UNAVAILABLE: 50301,
    SERVICE_DATABASE_UNAVAILABLE: 50302,
    SERVICE_CACHE_UNAVAILABLE: 50303,
    SERVICE_EMAIL_UNAVAILABLE: 50304,
    SERVICE_FILE_STORAGE_UNAVAILABLE: 50305,
    SERVICE_THIRD_PARTY_UNAVAILABLE: 50306,
};

// Error messages mapping
const ERROR_MESSAGES = {
    // Authentication Messages
    [ERROR_CODES.AUTH_TOKEN_MISSING]: 'Access token is required',
    [ERROR_CODES.AUTH_TOKEN_INVALID]: 'Invalid access token',
    [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Access token has expired',
    [ERROR_CODES.AUTH_TOKEN_MALFORMED]: 'Malformed access token',
    [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
    [ERROR_CODES.AUTH_USER_NOT_FOUND]: 'User account not found',
    [ERROR_CODES.AUTH_PASSWORD_INCORRECT]: 'Incorrect password',
    [ERROR_CODES.AUTH_EMAIL_NOT_VERIFIED]: 'Email address not verified',
    [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 'Account is temporarily locked',
    [ERROR_CODES.AUTH_ACCOUNT_SUSPENDED]: 'Account has been suspended',
    [ERROR_CODES.AUTH_ACCOUNT_DELETED]: 'Account has been deleted',
    [ERROR_CODES.AUTH_LOGIN_ATTEMPTS_EXCEEDED]: 'Too many login attempts',

    // Validation Messages
    [ERROR_CODES.VALIDATION_GENERAL_ERROR]: 'Validation error occurred',
    [ERROR_CODES.VALIDATION_MISSING_REQUIRED_FIELD]: 'Required field is missing',
    [ERROR_CODES.VALIDATION_INVALID_FORMAT]: 'Invalid format provided',
    [ERROR_CODES.VALIDATION_INVALID_LENGTH]: 'Invalid length',
    [ERROR_CODES.VALIDATION_INVALID_RANGE]: 'Value out of range',
    [ERROR_CODES.VALIDATION_INVALID_TYPE]: 'Invalid data type',
    [ERROR_CODES.VALIDATION_EMAIL_INVALID]: 'Invalid email address format',
    [ERROR_CODES.VALIDATION_EMAIL_DUPLICATE]: 'Email address already exists',
    [ERROR_CODES.VALIDATION_EMAIL_BLACKLISTED]: 'Email address is blacklisted',
    [ERROR_CODES.VALIDATION_PASSWORD_TOO_SHORT]: 'Password is too short',
    [ERROR_CODES.VALIDATION_PASSWORD_TOO_LONG]: 'Password is too long',
    [ERROR_CODES.VALIDATION_PASSWORD_NO_UPPERCASE]: 'Password must contain uppercase letter',
    [ERROR_CODES.VALIDATION_PASSWORD_NO_LOWERCASE]: 'Password must contain lowercase letter',
    [ERROR_CODES.VALIDATION_PASSWORD_NO_NUMBER]: 'Password must contain number',
    [ERROR_CODES.VALIDATION_PASSWORD_NO_SPECIAL_CHAR]: 'Password must contain special character',
    [ERROR_CODES.VALIDATION_PASSWORD_MISMATCH]: 'Passwords do not match',
    [ERROR_CODES.VALIDATION_PHONE_INVALID]: 'Invalid phone number format',
    [ERROR_CODES.VALIDATION_FILE_TYPE_INVALID]: 'Invalid file type',
    [ERROR_CODES.VALIDATION_FILE_SIZE_TOO_LARGE]: 'File size is too large',
    [ERROR_CODES.VALIDATION_ID_INVALID]: 'Invalid ID format',

    // Forbidden Messages
    [ERROR_CODES.FORBIDDEN_INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
    [ERROR_CODES.FORBIDDEN_ROLE_NOT_AUTHORIZED]: 'Role not authorized for this action',
    [ERROR_CODES.FORBIDDEN_RESOURCE_ACCESS_DENIED]: 'Access to resource denied',
    [ERROR_CODES.FORBIDDEN_ACCOUNT_INACTIVE]: 'Account is inactive',
    [ERROR_CODES.FORBIDDEN_ACCOUNT_PENDING]: 'Account is pending approval',
    [ERROR_CODES.FORBIDDEN_ACCOUNT_BANNED]: 'Account has been banned',

    // Not Found Messages
    [ERROR_CODES.NOT_FOUND_USER]: 'User not found',
    [ERROR_CODES.NOT_FOUND_ORGANIZATION]: 'Organization not found',
    [ERROR_CODES.NOT_FOUND_REVIEW]: 'Review not found',
    [ERROR_CODES.NOT_FOUND_MOU]: 'MOU not found',
    [ERROR_CODES.NOT_FOUND_ROADSHOW]: 'Roadshow not found',
    [ERROR_CODES.NOT_FOUND_FILE]: 'File not found',
    [ERROR_CODES.NOT_FOUND_RESOURCE]: 'Resource not found',
    [ERROR_CODES.NOT_FOUND_ENDPOINT]: 'API endpoint not found',

    // Conflict Messages
    [ERROR_CODES.CONFLICT_DUPLICATE_ENTRY]: 'Duplicate entry detected',
    [ERROR_CODES.CONFLICT_ORGANIZATION_ALREADY_EXISTS]: 'Organization already exists',
    [ERROR_CODES.CONFLICT_REVIEW_ALREADY_SUBMITTED]: 'Review already submitted',
    [ERROR_CODES.CONFLICT_MOU_ALREADY_SIGNED]: 'MOU already signed',
    [ERROR_CODES.CONFLICT_ROADSHOW_ALREADY_REGISTERED]: 'Already registered for roadshow',

    // Server Error Messages
    [ERROR_CODES.SERVER_INTERNAL_ERROR]: 'Internal server error',
    [ERROR_CODES.DATABASE_CONNECTION_ERROR]: 'Database connection failed',
    [ERROR_CODES.DATABASE_QUERY_ERROR]: 'Database query failed',
    [ERROR_CODES.FILE_UPLOAD_ERROR]: 'File upload failed',
    [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service error',
    [ERROR_CODES.EMAIL_SEND_FAILED]: 'Failed to send email',
};

// Helper function to get error message
const getErrorMessage = (errorCode, customMessage = null) => {
    return customMessage || ERROR_MESSAGES[errorCode] || 'Unknown error occurred';
};

// Helper function to get HTTP status from error code
const getHttpStatusFromErrorCode = (errorCode) => {
    const codeStr = errorCode.toString();

    if (codeStr.startsWith('401')) return 401;
    if (codeStr.startsWith('400')) return 400;
    if (codeStr.startsWith('403')) return 403;
    if (codeStr.startsWith('404')) return 404;
    if (codeStr.startsWith('409')) return 409;
    if (codeStr.startsWith('422')) return 422;
    if (codeStr.startsWith('429')) return 429;
    if (codeStr.startsWith('500')) return 500;
    if (codeStr.startsWith('503')) return 503;

    return 500; // Default to server error
};

module.exports = {
    ERROR_CODES,
    ERROR_MESSAGES,
    getErrorMessage,
    getHttpStatusFromErrorCode
};